// GENERATED FILE -- do not edit. Run `npm run rooms` after changing rooms/.
//
// Room art lives in `rooms/` as PNGs, which is what a person can paint and what
// both reference games use. It is compiled to TypeScript rather than fetched at
// runtime for two reasons: world generation stays synchronous, and the generator
// stays testable in Node without a DOM or a network.
//
// The rows below are the room art as glyphs, so a change to a room shows up as a
// readable diff instead of an opaque binary blob.

import type { EcotoneId, MaterialKind, ProvinceId } from "../config";

export type RoomMarker = "cache" | "anomaly" | "seam" | "survey" | "procedure" | "decor" | "random";

export interface RoomGlyph {
  name: string;
  /** The material this cell becomes, or null for open space and markers. */
  kind: MaterialKind | null;
  /** True when the cell takes whichever material the province at the stamp site uses. */
  host: boolean;
  marker: RoomMarker | null;
  /** Buried features cost a claim to reach; hanging ones do not. */
  markerHost: "rock" | "open" | null;
  /** Pins a facet's reflecting diagonal, so an authored lattice is coherent. */
  axis: 1 | -1 | null;
  /** Transparent cells leave the generated world exactly as it was. */
  transparent: boolean;
  open: boolean;
}

export const ROOM_GLYPHS: Record<string, RoomGlyph> = {
  "-": { name: "transparent", kind: null, host: false, marker: null, markerHost: null, axis: null, transparent: true, open: false },
  ".": { name: "open", kind: null, host: false, marker: null, markerHost: null, axis: null, transparent: false, open: true },
  "#": { name: "host rock", kind: null, host: true, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "c": { name: "chalk", kind: "chalk", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "s": { name: "slate", kind: "slate", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "k": { name: "coal seam", kind: "coalSeam", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "r": { name: "reef rock", kind: "reef", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "f": { name: "crystal facet", kind: "facet", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "/": { name: "facet NE-SW", kind: "facet", host: false, marker: null, markerHost: null, axis: 1, transparent: false, open: false },
  "\\": { name: "facet NW-SE", kind: "facet", host: false, marker: null, markerHost: null, axis: -1, transparent: false, open: false },
  "F": { name: "charged facet", kind: "chargedFacet", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "%": { name: "charged NE-SW", kind: "chargedFacet", host: false, marker: null, markerHost: null, axis: 1, transparent: false, open: false },
  "&": { name: "charged NW-SE", kind: "chargedFacet", host: false, marker: null, markerHost: null, axis: -1, transparent: false, open: false },
  "w": { name: "sapwood", kind: "sapwood", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "l": { name: "living block", kind: "living", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "b": { name: "spore bulb", kind: "sporeBulb", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "h": { name: "heartwood", kind: "heartwood", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "m": { name: "mirror slate", kind: "mirrorSlate", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "x": { name: "chalkroot", kind: "chalkroot", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "y": { name: "bloomcrystal", kind: "bloomcrystal", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "M": { name: "mechanism", kind: "mechanism", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "L": { name: "lander hull", kind: "lander", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "T": { name: "survey stake", kind: "stake", host: false, marker: null, markerHost: null, axis: null, transparent: false, open: false },
  "1": { name: "cache", kind: null, host: false, marker: "cache", markerHost: "rock", axis: null, transparent: false, open: false },
  "2": { name: "anomaly", kind: null, host: false, marker: "anomaly", markerHost: "open", axis: null, transparent: false, open: false },
  "3": { name: "rich seam", kind: null, host: false, marker: "seam", markerHost: "rock", axis: null, transparent: false, open: false },
  "4": { name: "survey data", kind: null, host: false, marker: "survey", markerHost: "open", axis: null, transparent: false, open: false },
  "5": { name: "procedure site", kind: null, host: false, marker: "procedure", markerHost: "open", axis: null, transparent: false, open: false },
  "*": { name: "decoration", kind: null, host: false, marker: "decor", markerHost: "open", axis: null, transparent: false, open: false },
  "?": { name: "random feature", kind: null, host: false, marker: "random", markerHost: "open", axis: null, transparent: false, open: false },
};

/** Footprint tiers, following Terraria's own point-of-interest / mini-biome ladder. */
export type RoomTier = "feature" | "chamber" | "hall";

export interface RoomTemplate {
  name: string;
  /**
   * Where this room may be stamped. A province id restricts it to that province, an
   * ecotone id to that ecotone only, and `any` allows it anywhere.
   */
  region: ProvinceId | EcotoneId | "any";
  tier: RoomTier;
  /**
   * Depth bands this room may be stamped in, from the `-bNN` filename tag.
   *
   * Gating is what makes depth read as progression rather than as more of the same: a
   * timbered drift belongs near the Landing and a cathedral does not. Most rooms are
   * ungated, because gating everything starves the tiers instead of shaping them.
   */
  bands: readonly number[];
  /** `-fixed`: this room's design depends on its literal materials, so never substitute. */
  fixed: boolean;
  /** `-rot`: this room's composition has no up-down commitment, so a quarter turn reads. */
  rotate: boolean;
  /** `-nomirror`: mirroring this room would break something in it. */
  mirror: boolean;
  width: number;
  height: number;
  rows: readonly string[];
}

export const ROOM_TEMPLATES: readonly RoomTemplate[] = [
  {
    name: "any-cistern",
    region: "any",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 12,
    height: 9,
    rows: [
      "------------",
      "---......---",
      "-..*.......-",
      "-..........-",
      "............",
      "..#......#..",
      "-...####...-",
      "-.#..?...#.-",
      "-##########-",
    ],
  },
  {
    name: "any-collapse",
    region: "any",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 12,
    height: 10,
    rows: [
      "----....----",
      "---......---",
      "-..........-",
      "-..........-",
      "...?........",
      "............",
      ".....###....",
      "-..###?###.-",
      "-.#########-",
      "--#########-",
    ],
  },
  {
    name: "any-crossroads",
    region: "any",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "----...........---",
      "--.?.............-",
      "-.......###.......",
      "-......##?##......",
      "-......#####......",
      "--......###....*.-",
      "---.............--",
      "-################-",
    ],
  },
  {
    name: "any-great-collapse",
    region: "any",
    tier: "hall",
    bands: [3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 36,
    height: 18,
    rows: [
      "----......--------------------------",
      "----......--.............-----------",
      "----.........................-------",
      "------.........................-----",
      "----.............................---",
      "---...............................--",
      "--..............?.......2..........-",
      "-...................................",
      "-...................................",
      "-.##................................",
      "-.######............................",
      "-.###1#####.........................",
      "--#####?#######.......#.......?....-",
      "--##########?######..###..........--",
      "--#####################....#.....---",
      "--###########################..-----",
      "--###########################-------",
      "--###########################-------",
    ],
  },
  {
    name: "any-old-stake",
    region: "any",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 9,
    height: 7,
    rows: [
      "---------",
      "--.....--",
      "-......*-",
      "....4....",
      "....T....",
      "-#######-",
      "-#######-",
    ],
  },
  {
    name: "any-rubble-choke",
    region: "any",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "---.....###......-",
      "-.......###.......",
      "-.?............##.",
      "-..............#1.",
      "-.......###.......",
      "-.......###.......",
      "--......###.......",
      "-################-",
    ],
  },
  {
    name: "any-shaft-junction",
    region: "any",
    tier: "hall",
    bands: [1, 2],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 36,
    height: 18,
    rows: [
      "-----------------------------.------",
      "---------------------------...------",
      "-------------------------.....------",
      "------------------.----......-------",
      "-------------..............---------",
      "----------....2...........?---------",
      "---------...................--------",
      "--------.....................----?--",
      "-----#-..#.................#..-#----",
      "-..................................-",
      "-..................................-",
      "-..................................-",
      "---1-#-..#.................#..-#----",
      "--------....?................-------",
      "---------.........4...?.....--------",
      "----------........T........---------",
      "--################################--",
      "--################################--",
    ],
  },
  {
    name: "any-spoil-heap",
    region: "any",
    tier: "feature",
    bands: [1, 2],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 11,
    height: 8,
    rows: [
      "-----.-----",
      "--.......--",
      "-........#-",
      ".........?.",
      ".........#.",
      ".........#.",
      "-.#?####..-",
      "-#########-",
    ],
  },
  {
    name: "any-timbered-drift",
    region: "any",
    tier: "chamber",
    bands: [1, 2],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "----...........---",
      "--..#...#...#?...-",
      "-.................",
      "-..4...........#..",
      "-..............#..",
      "--..#.?.#...#....-",
      "--##############--",
      "--##############--",
    ],
  },
  {
    name: "any-vent",
    region: "any",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: true,
    mirror: true,
    width: 9,
    height: 12,
    rows: [
      "---------",
      "--.....--",
      "-.*.....-",
      "-..#.#..-",
      "--.....--",
      "----.----",
      "----?----",
      "----.----",
      "--.....--",
      "-..#.#..-",
      "-.......-",
      "--.....--",
    ],
  },
  {
    name: "bloomshelf-bower",
    region: "bloomShelf",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 13,
    height: 10,
    rows: [
      "-------------",
      "---.......---",
      "--.........--",
      "-.....%.....-",
      "..?..y.y.....",
      "....y...y....",
      "...y.y3y.y...",
      "-.y.......y.-",
      "--.........--",
      "-yyyyyyyyyyy-",
    ],
  },
  {
    name: "bloomshelf-bud",
    region: "bloomShelf",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: true,
    mirror: true,
    width: 10,
    height: 8,
    rows: [
      "----------",
      "--......--",
      "-.*.....?-",
      "..........",
      "...yyyy...",
      "...y3.y...",
      "-...yy...-",
      "-yyyyyyyy-",
    ],
  },
  {
    name: "bloomshelf-lattice",
    region: "bloomShelf",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "---.....---.....--",
      "-.?............?..",
      "-....y...y...y...y",
      "-....y...y...y...y",
      "-...y...y%..y...y.",
      "-...y...y3y.y...y.",
      "--.y...y...y...y.-",
      "-yyyyyyyyyyyyyyyy-",
    ],
  },
  {
    name: "brightfault-bank",
    region: "brightFault",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "-------------.----",
      "---..............-",
      "--....?.m..mm.....",
      "-......mm..mm.....",
      "-.....mm.mm.mm....",
      "-....mm..3m..m*...",
      "-...mm........mm..",
      "--.mm..........mm-",
      "-mmmmmmmmmmmmmmmm-",
    ],
  },
  {
    name: "brightfault-mirror-nook",
    region: "brightFault",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 10,
    height: 8,
    rows: [
      "----------",
      "--......--",
      "-.?......-",
      ".......mm.",
      ".....mmm3.",
      "...mm.....",
      "-.m......-",
      "-mmmmmmmm-",
    ],
  },
  {
    name: "brightfault-shear",
    region: "brightFault",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 13,
    height: 10,
    rows: [
      "-------------",
      "---.......---",
      "--.........--",
      "-.mmmmmm....-",
      "..mmmmmm.mm..",
      ".........m3..",
      "..?..........",
      "-....mmmmmm.-",
      "--...mmmmmm--",
      "-mmmmmmmmmmm-",
    ],
  },
  {
    name: "chalkwarren-bays",
    region: "chalkWarren",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 13,
    height: 10,
    rows: [
      "-------------",
      "---.......---",
      "--.........--",
      "-..?.....*..-",
      ".............",
      ".............",
      "....s...s....",
      "-.xxsxxxsxxx-",
      "--xxsxxxsx3x-",
      "-xxxsxxxsxxx-",
    ],
  },
  {
    name: "chalkwarren-growth",
    region: "chalkWarren",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "----.........-----",
      "--..............--",
      "-.?.............*-",
      "-................-",
      "-....s.....s.....-",
      "-.xxxs.xxx.sxxxxx-",
      "--xxxsxxxxxsxx3xx-",
      "-xxxxsxxxxxsxxxxx-",
    ],
  },
  {
    name: "chalkwarren-root-pocket",
    region: "chalkWarren",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 10,
    height: 8,
    rows: [
      "----------",
      "--......--",
      "-.......?-",
      "..........",
      "..........",
      "..sxxxxs..",
      "-.xxx3xx.-",
      "-xxxxxxxx-",
    ],
  },
  {
    name: "karst-coal-pocket",
    region: "karst",
    tier: "feature",
    bands: [1, 2],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 10,
    height: 8,
    rows: [
      "----------",
      "--......--",
      "-......?.-",
      "..........",
      "..*.......",
      "...kcck...",
      "-..kkkk..-",
      "-cccccccc-",
    ],
  },
  {
    name: "karst-colonnade",
    region: "karst",
    tier: "hall",
    bands: [1, 2],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 36,
    height: 18,
    rows: [
      "------------------------------------",
      "------------..cccccccc...-----------",
      "--------cccccc........ccccccc-------",
      "----cccc.....................cccc---",
      "----..sss...sss...sss...sss...sss---",
      "---....s.....s.....s.....s.....s..--",
      "--.....s.....s....2s..*..s.....s...-",
      "-......s.....s.....s.....s.....s....",
      "-......s.....s.....s.....s.....s....",
      "-......s.....s.....s.....s.....s....",
      "-......s.....s.....s.....s.....s....",
      "-......s.....s.....s.....s.....s....",
      "--.....s.....s.....s.....s.....s.*.-",
      "---.*..s.....s.....s.....3.....s..--",
      "----...s.....s..*.ks.....s.....s.---",
      "------.s.....s.kkkkkkk...s.....s----",
      "--cccccscccccscccckscccccscccccscc--",
      "--cccccccc3ccccccccccccccccccccccc--",
    ],
  },
  {
    name: "karst-pinch",
    region: "karst",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "----.-------------",
      "--.....-sss......-",
      "-.......sss....cc.",
      "-.*............c1.",
      "...............cc.",
      "..................",
      "-.......sss.......",
      "-cccccccssscccccc-",
      "-cccccccssscccccc-",
    ],
  },
  {
    name: "karst-slate-bank",
    region: "karst",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------.----ss-----",
      "---.......ss------",
      "-....*...ss...cc.-",
      "-.......sk....c3..",
      "-.......ks........",
      "-......ks....*....",
      "-.....ks..........",
      "--...ks.....ccccc-",
      "-cccksscccccccccc-",
    ],
  },
  {
    name: "karst-slate-shelf",
    region: "karst",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 11,
    height: 8,
    rows: [
      "-----.-----",
      "--?......--",
      "-.........-",
      "..sssssss..",
      "........s..",
      "...c3......",
      "-.........-",
      "-ccccccccc-",
    ],
  },
  {
    name: "karst-stope",
    region: "karst",
    tier: "hall",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 36,
    height: 18,
    rows: [
      "------------------------------------",
      "--------.........-------------------",
      "-----...............----------------",
      "---..?................--------------",
      "--.ssssss...........2..-------------",
      "-......ss....................-------",
      "-......ss3ssss..................----",
      "............skkkkkkk..............--",
      "-...........sssssss.....?..........-",
      "-................ss.................",
      "--...............?ssssss............",
      "---...................ss............",
      "-----.................sssssss.......",
      "--------...................ss..?....",
      "--------------.............sssssss.-",
      "---------------.............3...ss--",
      "--cccccccccccccccccccccccccccccccc--",
      "--cccccccccccccccccccccccccccccccc--",
    ],
  },
  {
    name: "karst-survey-stakes",
    region: "karst",
    tier: "feature",
    bands: [1, 2],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 10,
    height: 8,
    rows: [
      "----------",
      "---.T..---",
      "-........-",
      "-........-",
      "....4*....",
      "-.T....T.-",
      "-cccccccc-",
      "-cccccccc-",
    ],
  },
  {
    name: "mirrorreef-cascade-chain",
    region: "mirrorreef",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: true,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "-------------.----",
      "----------.......-",
      "---...............",
      "--*............*..",
      "-.................",
      "-....\\.\\.\\....rr..",
      "-...&.\\.\\.&...r3..",
      "--.rrrrrrrrrrr...-",
      "-rrrrrrrrrrrrrrrr-",
    ],
  },
  {
    name: "mirrorreef-cathedral",
    region: "mirrorreef",
    tier: "hall",
    bands: [3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 36,
    height: 18,
    rows: [
      "------------------------------------",
      "------------.............-----------",
      "--------......rrrrrrrr.......-------",
      "------..rrrrrr...%&...rrrrrrr..-----",
      "----rrrr.....................rrrr---",
      "---.././...\\.\\..././...\\.\\..././..-\\",
      "--..././...\\.\\.../2/...\\.\\..././...\\",
      "-...../.....\\...../.....*...../.....",
      "-...../.....\\...../.....\\...../.....",
      "-...../.....\\...../.....\\...../.....",
      "-.....//....\\\\....//....\\\\....//....",
      "-...././...\\.\\..././...\\.\\..././...\\",
      "--.../*/...\\.\\..././...\\.\\..././*..\\",
      "---.././...\\.\\..././...\\.\\.3././..-\\",
      "----/.../.\\...\\*/.../.\\...\\./.../-\\-",
      "----/-../.\\...\\./.../.\\...\\./..-/-\\-",
      "--rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr--",
      "--rrrrrrrrr3rrrrrrrrrrrrrrrrrrrrrr--",
    ],
  },
  {
    name: "mirrorreef-charge-node",
    region: "mirrorreef",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: true,
    rotate: true,
    mirror: true,
    width: 9,
    height: 9,
    rows: [
      "---...---",
      "--.....--",
      "-......?-",
      "...\\\\\\...",
      "...\\&\\...",
      "...\\\\\\...",
      "-.......-",
      "-rrrrrrr-",
      "-rrrrrrr-",
    ],
  },
  {
    name: "mirrorreef-crossed-lattice",
    region: "mirrorreef",
    tier: "chamber",
    bands: [3, 4],
    fixed: true,
    rotate: true,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "---.....r1r.....--",
      "-.......rrr.......",
      "-...*../\\./\\..*...",
      "-.../../.%/.\\..\\..",
      "-../../..&..\\..\\..",
      "-../../../\\..\\..\\.",
      "--/../../.\\..\\..\\-",
      "-rrrrrrrrrrrrrrrr-",
    ],
  },
  {
    name: "mirrorreef-facet-vein",
    region: "mirrorreef",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 11,
    height: 8,
    rows: [
      "-----.-----",
      "--.......--",
      "-..?....rr-",
      "......//r3.",
      "....//.....",
      "..//.......",
      "-.........-",
      "-rrrrrrrrr-",
    ],
  },
  {
    name: "mirrorreef-fault-face",
    region: "mirrorreef",
    tier: "hall",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 36,
    height: 18,
    rows: [
      "------------------------------------",
      "-------.........--------------------",
      "----....................-------///--",
      "--..........................-//%//--",
      "-.........................//r%r-----",
      "-.................2.....////rrr-----",
      "......................////..rrr.----",
      "-................../////.........---",
      "-................/rrr/..3........?--",
      "--............////rrr..............-",
      "----?......./////.rrr...............",
      "----......////......................",
      "-----../rrr/........................",
      "-----///rrr...?.....................",
      "---///3.rrr.........................",
      "--///----..........................-",
      "--rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr--",
      "--rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr--",
    ],
  },
  {
    name: "mirrorreef-lattice-wall",
    region: "mirrorreef",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "----...-----------",
      "--............-//-",
      "--.*.......////..-",
      "-.......///.......",
      "-...////...rr..*..",
      "-.//.......3r.....",
      "--..rr.....rr....-",
      "-rrrrrrrrrrrrrrrr-",
    ],
  },
  {
    name: "mirrorreef-mirror-funnel",
    region: "mirrorreef",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 12,
    height: 10,
    rows: [
      "-----..-----",
      "-\\......../-",
      "-.\\..*.../.-",
      "-.\\....../.-",
      "...\\..../...",
      "....\\../....",
      "-...\\../...-",
      "-....\\/....-",
      "--..r1rr..--",
      "----rrrr----",
    ],
  },
  {
    name: "rootwarren-bulb-cluster",
    region: "rootwarren",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 10,
    height: 8,
    rows: [
      "----------",
      "--......--",
      "-..wwww..-",
      "-..b.bb..-",
      "..........",
      "-.?......-",
      "-wwwwwwww-",
      "-wwwwwwww-",
    ],
  },
  {
    name: "rootwarren-bulb-gallery",
    region: "rootwarren",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "---------.--------",
      "---w..w..w..w..w--",
      "--.b..b..b..b..b.-",
      "--...............-",
      "-.................",
      "-...*..........ll.",
      "--......www....ll-",
      "---.....w1w....ll-",
      "-wwwwwwwwwwwwwwww-",
    ],
  },
  {
    name: "rootwarren-creep",
    region: "rootwarren",
    tier: "chamber",
    bands: [3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "----..........----",
      "--..........h...--",
      "-...h..*....hlll.-",
      "-...h.......hlll.-",
      "-...h4.....lll1l.-",
      "-...hlll.b.lllll.-",
      "--.hhhhhhhhhhhhh--",
      "-----........-----",
    ],
  },
  {
    name: "rootwarren-heartwood-knot",
    region: "rootwarren",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: true,
    mirror: true,
    width: 13,
    height: 11,
    rows: [
      "------.------",
      "---.......---",
      "--.........--",
      "-.*.hhhhh...-",
      "-..h.....h..-",
      "...h.l3l.h...",
      "-..h.....h..-",
      "-...hhhhh...-",
      "--.........--",
      "-wwwwwwwwwww-",
      "-wwwwwwwwwww-",
    ],
  },
  {
    name: "rootwarren-hollow-bole",
    region: "rootwarren",
    tier: "hall",
    bands: [3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 36,
    height: 18,
    rows: [
      "------------------------------------",
      "------------......h......-----------",
      "--------...hhhhhhhhhhhhhhh...-------",
      "------...hhh.............hhh...-----",
      "----...hh..b......b......b..hh...---",
      "---...lll..................lllh...--",
      "--...hlll..................lll.h...-",
      "-.....lll.........2........lll......",
      "-.....lll..................lll......",
      "-.....*ll..............*...lll......",
      "-.....lll..................lll......",
      "-.....lll....*.............lll......",
      "--...hlll..................lll.h...-",
      "---...ll3lllllllllllllllllllll*...--",
      "----..llllllllllllllllllllllll...---",
      "------...hhh.............hhh...-----",
      "--wwwwwwwwwhhhhhhh3hhhhhhhwwwwwwww--",
      "--wwwwwwwwwwwwwwwwhwwwwwwwwwwwwwww--",
    ],
  },
  {
    name: "rootwarren-pruning-cells",
    region: "rootwarren",
    tier: "chamber",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 18,
    height: 9,
    rows: [
      "------------------",
      "------------.....-",
      "-----.............",
      "--*.............*.",
      "--...h...h...h....",
      "-....h...3...h....",
      "-....hlllh...hll..",
      "--.llhlllhlllhll.-",
      "-wwwwhwwwhwwwhwww-",
    ],
  },
  {
    name: "rootwarren-regrowth-scar",
    region: "rootwarren",
    tier: "feature",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 11,
    height: 8,
    rows: [
      "-----.-----",
      "--.......--",
      "-.?.......-",
      "...........",
      ".......l...",
      "..lll.l1l..",
      "-..hhhhlhh-",
      "-wwwwwwwww-",
    ],
  },
  {
    name: "rootwarren-root-vault",
    region: "rootwarren",
    tier: "hall",
    bands: [1, 2, 3, 4],
    fixed: false,
    rotate: false,
    mirror: true,
    width: 36,
    height: 18,
    rows: [
      "------------------------------------",
      "------------.............-----------",
      "--------.....................-------",
      "------............2............-----",
      "----l...........................l---",
      "--lllll..h..llll..h..llll..h..lllll-",
      "--llll3hhbhhllllhhbhhllllhhbhhlllll-",
      "-.lllllh...hllllh...hllllh...hlllll.",
      "-...lhh.....hhhh.....hhhh.....hhl...",
      "-....h.......hh.......hh.......h....",
      "-...hh.......hh.......hh.......hh...",
      "-...h........h........h........?h...",
      "--..h........h........h.........h..-",
      "---.h........h........h.........h.--",
      "----h........?........h?........h---",
      "-----.............3.............----",
      "--www...........................ww--",
      "--www...........................ww--",
    ],
  },
];
